[Interface]
PrivateKey = aHYzFi6JsfZv7yzs4kGGPBq1IpWvsz52520vS/OD8nk=
Address = 10.0.0.2/24

[Peer]
PublicKey = F2pYsG3rrTWxx5eZBSTz2sDIvKgSvN8rVsCyzMRwxjo=
Endpoint = 16.171.181.60:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25